old_sound_rabbit_mq:
    connections:
        default:
            host:     'localhost'
            port:     5672
            user:     'guest'
            password: 'guest'
            vhost:    '/'
    producers:
        loggerProducer:
            connection:       default
            exchange_options: {name: 'logger', type: direct}
    consumers:
        logger:
            connection:       default
            exchange_options: {name: 'logger', type: direct}
            queue_options:    {name: 'logger'}
            callback:         App\MessageHandler\LogMessageHandler